name = "project_zero"
version = "1.1.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
dot_env = ">= 1.2.0 and < 2.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_http = ">= 3.7.0 and < 5.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre = ">= 5.0.0 and < 6.0.0"
mist = ">= 4.0.0 and < 6.0.0"
wisp = ">= 2.0.0 and < 3.0.0"
pog = ">= 4.1.0 and < 5.0.0"
gleam_otp = ">= 1.2.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
olive = { git = "git@github.com:brian-penguin/olive.git", ref = "main" }
cigogne = ">= 5.0.3 and < 6.0.0"
