name: gleam-test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.6.3"
          rebar3-version: "3"
          # elixir-version: "1.15.4"
      - name: Cache Gleam dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/gleam
            ~/.cache/hex
          key: ${{ runner.os }}-gleam-${{ hashFiles('manifest.toml') }}
          restore-keys: |
            ${{ runner.os }}-gleam-
      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test
